name: Deploy Website

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and deploy
        run: |
          echo "Deploying website..."

